### ISSUE TITLE
Listen to GitHub Webhooks

### ISSUE THREAD

**Issue by PatrickHeneise** [GitEvents/gitevents#21]
Check out:

https://github.com/barcelona-js/node/blob/master/routes/talks.js#L69

This handles a GitHub web hook for an issue. But it's not very flexible at the moment, in terms of integrations.

**Comment by PatrickHeneise** [comment]
webhook data: https://github.com/barcelona-js/node/blob/master/tests/data/labeled.json

**Comment by bpedro** [comment]
I'm now working on this one.
