### ISSUE TITLE
GitEvents Logo

### ISSUE THREAD

**Issue by PatrickHeneise** [GitEvents/gitevents#47]
Just a small thing, but would be cool to have a nice picture up. Suggestions?

**Comment by iancrowther** [comment]
@maxwellito @tancredi - I know you guys are busy.. buuut

**Comment by maxwellito** [comment]
Mmmmm... I'm thinking about it.

Recommendations? Guidelines? Which format?

**Comment by iancrowther** [comment]
none of the above!! you have artistic licence here completely

**Comment by maxwellito** [comment]
To be sure to understand the concept: it's a logo for this repo, which is a node script to find events and create a meetup event from them? Am I right?

**Comment by iancrowther** [comment]
so this is a gtthub org which uses node to help event organisers adminiter speakers.  Their is a plugin architecture to enable plugins such as twitter, but the core is submit an issue -> do something eg tweet

**Comment by iancrowther** [comment]
its a bot if that helps..

**Comment by iancrowther** [comment]
there should also be a module that "gets" processes and formats talk data which we can re-use from the LNUG website.  eventually we can extend this to get venue data, event details etc but for now its just the bot

**Comment by maxwellito** [comment]
I have to admit, I really have no idea. 

The only thing I had in mind was an event ticket with a git logo on it
![sans-titre---1](https://cloud.githubusercontent.com/assets/1097232/5865457/67c5e77c-a281-11e4-9012-5ba12ab51b76.png)

The other one is a kind of 'git' machine generating "Hello, my name is" stickers.
![sans-titre---12](https://cloud.githubusercontent.com/assets/1097232/5865497/af8071a4-a281-11e4-9d28-8adedff3c544.png)

My lack of creativity is at his best. Any idea is MORE THEN WELCOME.

**Comment by ifraixedes** [comment]
I like first one ;D it's simple and probably easy to generate different ones to match backgrounds, but I'm not designer at all.

**Comment by iancrowther** [comment]
@maxwellito love the first one.  Can the assets be checked in and prepped in the following ways:

- github org logo
- gravatar (twitter etc)
- transparent for websites etc
- favicon?

Although I like the concept of the second one, the message is not being conveyed clearly enough.

Another amazing job chief :-)

**Comment by PatrickHeneise** [comment]
Both are pretty cool for a first try. I guess the first is better since it can be included everywhere. There could be a black, white and coloured version.

**Comment by maxwellito** [comment]
Just before the final vote, I wanted to retry the second idea
![sans-titre---2](https://cloud.githubusercontent.com/assets/1097232/5889484/9de876de-a421-11e4-9b24-f2cbe8ad824d.png)

**Comment by ifraixedes** [comment]
@maxwellito it looks nice, my only worries if it would allow to be embedded everywhere as @PatrickHeneise commented, I know that it would require some tweaks, but how much work can they require?

**Comment by maxwellito** [comment]
First, agree all on what you would like or would change. Then I'll make the other versions. It's not really complex to create a black and white version.

I also like my first try but it might be difficult to render on small sizes.

**Comment by PatrickHeneise** [comment]
maybe a bit more "information distribution" flair than just the git logo would be cool?

**Comment by ifraixedes** [comment]
A bit more information it will be good, however I guess that only the wide versions could have it.
I like the last one more than the first one, because it's a ticket printer, and from my own point of view approaches more the GitEvents than a single ticket.

**Comment by iancrowther** [comment]
@maxwellito the issue i have with the last two are the meetup badge.  we should be a little more generic as were moving into that space bit by bit

**Comment by maxwellito** [comment]
@iancrowther It's true, it remind the meetup badge. But this "Hi my name is" badge is the best symbol to represent an event. Except that, I only see a calendar, not sure how to combine it with a bot.

@ifraixedes & @PatrickHeneise any ideas on how could I represent 'information distribution'?

**Comment by PatrickHeneise** [comment]
@maxwellito I'd be a designer if I would :P. Splitting a ticket in 2? 'cloning' a ticket? cloning an event/calendar entry? 'forking' it? I'm not sure.

**Comment by iancrowther** [comment]
Let go with number 1 @maxwellito

**Comment by PatrickHeneise** [comment]
:+1:

**Comment by maxwellito** [comment]
Here is what I have. What should I do? Make a PR? Post them here?

gitevents_favicon_16.png
gitevents_logo.svg
gitevents_logo_black_800.png
gitevents_logo_white_800.png

**Comment by iancrowther** [comment]
PR

**Comment by ifraixedes** [comment]
If PR is, check if those are OK with MIT license for you, otherwise add a new one for those for example one less tied to software as Creative Commons.

**Comment by maxwellito** [comment]
https://github.com/GitEvents/gitevents/pull/51

Don't worry about the license. MIT is perfectly fine with me :-)
