### ISSUE TITLE
can we change the org name to lowecase

### ISSUE THREAD

**Issue by iancrowther** [GitEvents/gitevents#48]
its sending my OCD crazy 

http://i.giphy.com/cMV9akgudJiRW.gif

**Comment by PatrickHeneise** [comment]
gite-vents? gi-tevents? just trying to help non-techs on how to pronounce it ... really that bad?

**Comment by iancrowther** [comment]
gitevents/gitevents is fine chief..

**Comment by PatrickHeneise** [comment]
Alright. Don't tell that GitHub :P
