### ISSUE TITLE
setup email and dns

### ISSUE THREAD

**Issue by iancrowther** [GitEvents/gitevents#49]
i bought the following domains

- gitevents.org
- gitevents.com
- gitevents.co.uk

**Comment by iancrowther** [comment]
@PatrickHeneise which to use? org or com?  others are for redirects

**Comment by PatrickHeneise** [comment]
You think it's necessary? We can just create a gh-page and be github.io/gitevents.

**Comment by iancrowther** [comment]
its for a support email address 

eg contact@gitevents

also for redirects and to prevent type squatters..

**Comment by iancrowther** [comment]
id rather have them before promoting :-)

**Comment by PatrickHeneise** [comment]
Since we're git-driven, shouldn't be support be through GitHub issues? :P

**Comment by ifraixedes** [comment]
I have the same doubt than @PatrickHeneise 
However with a domain the gh-page may be more attractive as some projects do (e.g. [mocha](http://mochajs.org/))

**Comment by iancrowther** [comment]
no rush, we have them bagged for a future date..
