### ISSUE TITLE
create Meetup module

### ISSUE THREAD

**Issue by PatrickHeneise** [GitEvents/gitevents#7]
Create meetup events, automatically announce them etc. when a milestone is created and an issue assigned.

**Comment by iancrowther** [comment]
see https://github.com/barcelona-js/gitup/issues/8

**Comment by Miz85** [comment]
Hi everyone !

I'm going to start working on a meetup module.

**Comment by Miz85** [comment]
Hi ! 

I just merged changes into the GitEvents/gitevents-meetup repo. 

I still have to write proper documentation & tests but it should work if someone wants to try calling it. You can find an example of how I called it including configuration and test data there: https://github.com/GitEvents/gitevents-meetup/blob/master/app.js

Let me know how it goes !

Cheers.

**Comment by iancrowther** [comment]
brilliant - many thanks
